export type Bit = { id: string; label: string; tags: string };
export type NsfwGroup = "Creatures" | "Positions" | "Sex" | "BDSM" | "Taboo" | "Horror";
export type NsfwBit = Bit & { group: NsfwGroup };

export const FACE_MORE: Bit[] = [
  { id: "hair-brown", label: "Brown hair", tags: "long brown hair" },
  { id: "hair-auburn", label: "Auburn", tags: "auburn hair, copper shine" },
  { id: "hair-strawberry", label: "Strawberry", tags: "strawberry blonde hair" },
  { id: "hair-platinum", label: "Platinum", tags: "platinum blonde hair" },
  { id: "hair-grey", label: "Grey hair", tags: "grey hair, salt and pepper" },
  { id: "hair-purple", label: "Purple hair", tags: "purple hair" },
  { id: "hair-green", label: "Green hair", tags: "green hair" },
  { id: "hair-ombre", label: "Ombre", tags: "ombre hair, dark roots, pale ends" },
  { id: "hair-twotone", label: "Two-tone", tags: "two-tone hair, split dye" },
  { id: "hair-highlights", label: "Highlights", tags: "highlighted hair" },
  { id: "hair-bob", label: "Bob", tags: "bob cut, jaw length" },
  { id: "hair-wolf", label: "Wolf cut", tags: "wolf cut, shaggy layers" },
  { id: "hair-hime", label: "Hime", tags: "hime cut, blunt bangs, straight" },
  { id: "hair-bangs", label: "Bangs", tags: "blunt bangs" },
  { id: "hair-curtain", label: "Curtain bangs", tags: "curtain bangs" },
  { id: "hair-afro", label: "Afro", tags: "afro, tight coils, volume" },
  { id: "hair-locs", label: "Locs", tags: "locs, well-kept" },
  { id: "hair-cornrows", label: "Cornrows", tags: "cornrows" },
  { id: "hair-buzz", label: "Buzz", tags: "buzz cut, scalp visible" },
  { id: "hair-mullet", label: "Mullet", tags: "mullet" },
  { id: "hair-buns", label: "Space buns", tags: "space buns" },
  { id: "hair-lowtail", label: "Low tail", tags: "low ponytail" },
  { id: "hair-sidetail", label: "Side tail", tags: "side ponytail" },
  { id: "hair-wavy", label: "Wavy", tags: "wavy hair" },
  { id: "hair-curly", label: "Curly", tags: "curly hair, defined curls" },
  { id: "hair-straight", label: "Straight", tags: "pin-straight long hair" },
  { id: "hair-wind", label: "Wind-swept", tags: "wind-swept hair" },
  { id: "eyes-hazel", label: "Hazel eyes", tags: "hazel eyes" },
  { id: "eyes-grey", label: "Grey eyes", tags: "grey eyes" },
  { id: "eyes-amber", label: "Amber eyes", tags: "amber eyes" },
  { id: "eyes-black", label: "Black eyes", tags: "black eyes, dark irises" },
  { id: "eyes-pink", label: "Pink eyes", tags: "pink eyes" },
  { id: "eyes-glow", label: "Glowing eyes", tags: "glowing eyes" },
  { id: "eyes-empty", label: "Empty eyes", tags: "empty eyes, no light" },
  { id: "eyes-teary", label: "Teary", tags: "teary eyes, wet lashes" },
  { id: "eyes-heavy", label: "Heavy lids", tags: "heavy-lidded eyes" },
  { id: "eyes-upturn", label: "Upturned", tags: "upturned eyes" },
  { id: "eyes-downturn", label: "Downturned", tags: "downturned eyes" },
  { id: "eyes-fox", label: "Fox eyes", tags: "fox eyes, long outer corner" },
  { id: "eyes-doe", label: "Doe eyes", tags: "doe eyes, large iris" },
  { id: "exp-pleasure", label: "Pleasure", tags: "face of pleasure, brows up, mouth open" },
  { id: "exp-ecstasy", label: "Ecstasy", tags: "ecstasy, eyes rolled, gasping" },
  { id: "exp-anger", label: "Angry", tags: "angry, bared teeth, glare" },
  { id: "exp-fear", label: "Afraid", tags: "afraid, wide eyes, tense mouth" },
  { id: "exp-defiant", label: "Defiant", tags: "defiant stare, jaw set" },
  { id: "exp-beg", label: "Begging", tags: "begging look, wet eyes" },
  { id: "exp-vacant", label: "Vacant", tags: "vacant stare, used, empty" },
  { id: "exp-laugh", label: "Laughing", tags: "laughing, teeth, crinkled eyes" },
  { id: "exp-sleep", label: "Asleep look", tags: "eyes closed, slack mouth, asleep look, adult" },
  { id: "exp-snarl", label: "Snarl", tags: "snarl, canines, feral" },
  { id: "exp-whisper", label: "Whisper", tags: "leaning in, lips parted" },
  { id: "exp-orgasm", label: "Orgasm face", tags: "orgasm face, shaking, wrecked" },
  { id: "exp-pain", label: "Pain", tags: "pain on the face, flinch, still going" },
  { id: "exp-shame", label: "Shame", tags: "looking away, shame, still doing it" },
  { id: "mk-redlip", label: "Red lip", tags: "red lipstick, sharp" },
  { id: "mk-gothic", label: "Gothic makeup", tags: "gothic makeup, black lip, pale" },
  { id: "mk-gyaru", label: "Gyaru", tags: "gyaru makeup, circle lenses, tan" },
  { id: "mk-winged", label: "Winged liner", tags: "winged eyeliner" },
  { id: "mk-gloss", label: "Gloss", tags: "lip gloss, wet mouth" },
  { id: "acc-glasses", label: "Glasses", tags: "glasses, frames on the nose" },
  { id: "acc-round", label: "Round glasses", tags: "round glasses" },
  { id: "acc-sun", label: "Sunglasses", tags: "sunglasses pushed up" },
  { id: "acc-patch", label: "Eyepatch", tags: "eyepatch" },
  { id: "acc-nose", label: "Nose ring", tags: "nose ring" },
  { id: "acc-lipring", label: "Lip ring", tags: "lip ring" },
  { id: "acc-ears", label: "Ear stack", tags: "ear piercings, stacked" },
  { id: "acc-fangs", label: "Fangs", tags: "fangs, slight" },
  { id: "acc-horns", label: "Small horns", tags: "small horns from the hairline" },
  { id: "face-tired", label: "Tired", tags: "dark circles, tired adult face" },
  { id: "face-aged", label: "Lines", tags: "laugh lines, adult face, lived-in" },
  { id: "face-softjaw", label: "Soft jaw", tags: "soft jaw, round chin" },
  { id: "face-fullips", label: "Full lips", tags: "full lips" },
  { id: "face-thinlips", label: "Thin lips", tags: "thin lips" },
  { id: "face-dimple", label: "Dimples", tags: "dimples" },
  { id: "face-gap", label: "Tooth gap", tags: "tooth gap" },
];

export const BODY_MORE: Bit[] = [
  { id: "body-hourglass", label: "Hourglass", tags: "hourglass figure, bust and hips" },
  { id: "body-pear", label: "Pear", tags: "pear shape, hips wider than bust" },
  { id: "body-apple", label: "Apple", tags: "soft middle, full bust" },
  { id: "body-rect", label: "Athletic rectangle", tags: "straight figure, athletic" },
  { id: "body-bbw", label: "BBW", tags: "bbw, fat adult, rolls, heavy breasts, 18+" },
  { id: "body-chubby", label: "Chubby", tags: "chubby adult, soft belly" },
  { id: "body-twink", label: "Twink", tags: "slim adult male, little body hair, 18+" },
  { id: "body-bara", label: "Bara", tags: "muscular hairy adult male, thick, 18+" },
  { id: "body-futa", label: "Futa body", tags: "futanari body, breasts and cock, adult" },
  { id: "body-androg", label: "Andro", tags: "androgynous adult body" },
  { id: "body-pregnant", label: "Pregnant", tags: "pregnant adult, swollen belly, 18+" },
  { id: "body-post", label: "Postpartum", tags: "postpartum adult, soft belly, 18+" },
  { id: "chest-perk", label: "Perky", tags: "perky breasts, high set" },
  { id: "chest-sag", label: "Soft hang", tags: "natural hang, soft breasts" },
  { id: "chest-puffy", label: "Puffy nipples", tags: "puffy nipples, wide areola" },
  { id: "chest-invert", label: "Inverted nipples", tags: "inverted nipples" },
  { id: "chest-areola", label: "Wide areola", tags: "wide dark areola" },
  { id: "chest-pierced", label: "Pierced nipples", tags: "nipple piercings, bars" },
  { id: "chest-milk", label: "Leaking", tags: "milk leaking from nipples" },
  { id: "ass-bubble", label: "Bubble ass", tags: "bubble butt, round, lifted" },
  { id: "ass-flat", label: "Flat ass", tags: "flat ass, athletic" },
  { id: "ass-huge", label: "Huge ass", tags: "huge ass, heavy, clap" },
  { id: "ass-cell", label: "Cellulite", tags: "cellulite, real skin, thighs" },
  { id: "gen-pussy", label: "Pussy", tags: "pussy in view, labia, clit" },
  { id: "gen-innie", label: "Innie", tags: "innie pussy, neat" },
  { id: "gen-outie", label: "Outie", tags: "outie labia, pronounced" },
  { id: "gen-wet", label: "Soaked", tags: "soaked pussy, juices on thighs" },
  { id: "gen-cock", label: "Cock", tags: "cock out, veins, heavy" },
  { id: "gen-huge", label: "Huge cock", tags: "huge cock, thick, unrealistic size" },
  { id: "gen-uncut", label: "Uncut", tags: "uncut cock, foreskin" },
  { id: "gen-cut", label: "Cut", tags: "cut cock, exposed head" },
  { id: "gen-balls", label: "Heavy balls", tags: "heavy balls, tight sac" },
  { id: "body-pubes", label: "Pubes", tags: "pubic hair, natural" },
  { id: "body-shaved", label: "Shaved", tags: "shaved, bare" },
  { id: "body-strip", label: "Landing strip", tags: "landing strip" },
  { id: "body-hair", label: "Body hair", tags: "body hair, underarms, legs" },
  { id: "body-smooth", label: "Smooth", tags: "smooth skin, shaved body" },
  { id: "mod-navel", label: "Navel ring", tags: "navel piercing" },
  { id: "mod-clit", label: "Clit piercing", tags: "clit hood piercing" },
  { id: "mod-ampallang", label: "Cock piercing", tags: "Prince Albert piercing" },
  { id: "skin-vitiligo", label: "Vitiligo", tags: "vitiligo, patterned skin" },
  { id: "skin-stretch", label: "Stretch marks", tags: "stretch marks on hips and breasts" },
  { id: "skin-flush", label: "Flushed body", tags: "flushed chest and neck" },
  { id: "skin-hickey", label: "Hickeys", tags: "hickeys on neck and breasts" },
  { id: "skin-scrape", label: "Rug burn", tags: "rug burn, floor marks" },
  { id: "body-veins", label: "Veins", tags: "veins on hands and cock" },
  { id: "body-waist", label: "Tiny waist", tags: "tiny waist, exaggerated" },
  { id: "body-shoulders", label: "Broad shoulders", tags: "broad shoulders" },
  { id: "body-narrow", label: "Narrow shoulders", tags: "narrow shoulders" },
  { id: "body-longlegs", label: "Long legs", tags: "long legs" },
  { id: "body-thickthigh", label: "Thick thighs", tags: "thick thighs touching" },
];

export const CLOTHES_MORE: Bit[] = [
  { id: "cl-bikini", label: "Bikini", tags: "bikini, strings, pulled aside" },
  { id: "cl-micro", label: "Micro bikini", tags: "micro bikini, barely covering" },
  { id: "cl-bunny", label: "Bunny", tags: "bunny suit, fishnets, cuffs, ears" },
  { id: "cl-cat", label: "Cat lingerie", tags: "cat ears, tail plug, lingerie" },
  { id: "cl-witchhat", label: "Witch hat", tags: "witch hat, nothing else" },
  { id: "cl-lab", label: "Lab coat", tags: "lab coat open, nude under" },
  { id: "cl-sweater", label: "Sweater", tags: "oversized sweater, thighs bare" },
  { id: "cl-turtle", label: "Turtleneck", tags: "turtleneck, no bottoms" },
  { id: "cl-crop", label: "Crop top", tags: "crop top, underboob, no bra" },
  { id: "cl-yoga", label: "Yoga pants", tags: "yoga pants pulled down" },
  { id: "cl-sport", label: "Sports bra", tags: "sports bra shoved up" },
  { id: "cl-cheer", label: "Cheer (adult)", tags: "adult cheer uniform, skirt up, 18+" },
  { id: "cl-qipao", label: "Qipao", tags: "qipao slit to the hip" },
  { id: "cl-sari", label: "Sari", tags: "sari falling off the shoulder" },
  { id: "cl-hanfu", label: "Hanfu", tags: "hanfu loose, chest bare" },
  { id: "cl-lolita", label: "Gothic lolita", tags: "gothic lolita dress hiked, adult 18+" },
  { id: "cl-punk", label: "Punk", tags: "punk, ripped, straps, boots" },
  { id: "cl-choker", label: "Choker", tags: "choker, otherwise nude" },
  { id: "cl-pasties", label: "Pasties", tags: "pasties, thong" },
  { id: "cl-tape", label: "Tape", tags: "bondage tape, X over nipples" },
  { id: "cl-crotchless", label: "Crotchless", tags: "crotchless panties, open" },
  { id: "cl-opencup", label: "Open cup", tags: "open-cup bra, nipples out" },
  { id: "cl-harness", label: "Body harness", tags: "body harness, straps, rings" },
  { id: "cl-strait", label: "Straitjacket", tags: "straitjacket, open at the hips" },
  { id: "cl-gown", label: "Hospital gown", tags: "hospital gown, open back" },
  { id: "cl-wedding", label: "Wedding torn", tags: "wedding dress torn, ruined" },
  { id: "cl-widow", label: "Widow", tags: "black veil, mourning dress open" },
  { id: "cl-santa", label: "Santa", tags: "santa lingerie, fur trim" },
  { id: "cl-police", label: "Police", tags: "police uniform half off, cuffs" },
  { id: "cl-military", label: "Military", tags: "military fatigues open, dog tags" },
  { id: "cl-fire", label: "Turnout", tags: "firefighter turnout coat, nothing under" },
  { id: "cl-waitress", label: "Waitress", tags: "waitress apron, skirt up" },
  { id: "cl-flight", label: "Flight attendant", tags: "flight attendant scarf, skirt up" },
  { id: "cl-pencil", label: "Pencil skirt", tags: "pencil skirt around the thighs" },
  { id: "cl-bike", label: "Bike shorts", tags: "bike shorts pulled aside" },
  { id: "cl-onesie", label: "Onesie open", tags: "onesie unzipped, adult 18+" },
  { id: "cl-corset", label: "Corset", tags: "corset, cinched, no bottoms" },
  { id: "cl-garter", label: "Garter", tags: "garter belt, stockings, no panties" },
  { id: "cl-thong", label: "Thong", tags: "thong pulled aside" },
  { id: "cl-noneund", label: "No underwear", tags: "no underwear under the clothes" },
  { id: "cl-shirtfuck", label: "Shirt lift", tags: "shirt lifted over breasts" },
  { id: "cl-pantsankle", label: "Pants ankles", tags: "pants around the ankles" },
  { id: "cl-onebreast", label: "One breast out", tags: "one breast out, clothes still on" },
  { id: "cl-wetshirt", label: "Wet shirt", tags: "wet white shirt, see-through" },
  { id: "cl-scarf", label: "Scarf only", tags: "scarf, otherwise nude, winter" },
  { id: "cl-gloves", label: "Opera gloves", tags: "opera gloves, nude body" },
  { id: "cl-mask", label: "Mask", tags: "mask, identity hidden, nude" },
  { id: "cl-blind", label: "Blindfold on", tags: "blindfold, otherwise dressed or not" },
  { id: "cl-plug", label: "Plugged", tags: "butt plug, tail, clothes on" },
  { id: "cl-vibe", label: "Vibe in", tags: "vibrator still in, clothes rumpled" },
  { id: "cl-leash", label: "Leash on", tags: "collar and leash, dressed or not" },
  { id: "cl-tie", label: "His tie", tags: "wearing his tie, nothing else" },
  { id: "cl-jacket", label: "Jacket only", tags: "leather jacket, nothing under" },
  { id: "cl-hoodieup", label: "Hood up", tags: "hoodie up, face in shadow, nude legs" },
  { id: "cl-socks", label: "Socks only", tags: "socks only" },
  { id: "cl-boots2", label: "Thigh boots", tags: "thigh-high boots, nothing else" },
];

export const PLACE_MORE: Bit[] = [
  { id: "pl-stall", label: "Bathroom stall", tags: "bathroom stall, graffiti, cramped" },
  { id: "pl-fitting", label: "Fitting room", tags: "fitting room, mirror, curtain half" },
  { id: "pl-elevator", label: "Elevator", tags: "elevator, camera in the corner, stopped" },
  { id: "pl-subway", label: "Subway", tags: "empty subway car, night, poles" },
  { id: "pl-bus", label: "Bus", tags: "back of the night bus, fogged window" },
  { id: "pl-plane", label: "Plane toilet", tags: "airplane lavatory, cramped, explicit" },
  { id: "pl-tent", label: "Tent", tags: "tent, sleeping bags, flashlight" },
  { id: "pl-beach", label: "Night beach", tags: "night beach, wet sand, moon" },
  { id: "pl-pool", label: "Pool", tags: "pool edge at night, wet tile" },
  { id: "pl-jacuzzi", label: "Jacuzzi", tags: "jacuzzi, steam, bubbles" },
  { id: "pl-sauna", label: "Sauna", tags: "sauna, wood, heat, sweat" },
  { id: "pl-locker", label: "Locker room", tags: "locker room, benches, steam" },
  { id: "pl-gym", label: "Gym after", tags: "gym after hours, mats, weights" },
  { id: "pl-class", label: "Classroom", tags: "empty classroom at night, desks, adult 18+" },
  { id: "pl-lecture", label: "Lecture hall", tags: "lecture hall, projector glow, adult 18+" },
  { id: "pl-library2", label: "Stacks", tags: "library stacks, between shelves" },
  { id: "pl-server", label: "Server room", tags: "server room, cold, blinking lights" },
  { id: "pl-park", label: "Parking garage", tags: "parking garage, concrete, one car" },
  { id: "pl-site", label: "Construction", tags: "construction site at night, plastic sheet" },
  { id: "pl-yacht", label: "Yacht", tags: "yacht cabin, ocean through porthole" },
  { id: "pl-castle", label: "Castle bed", tags: "castle bedroom, furs, stone, fire" },
  { id: "pl-snow", label: "Snow cabin", tags: "snowbound cabin, frost on glass" },
  { id: "pl-desert", label: "Desert night", tags: "desert night, cold, stars, blanket" },
  { id: "pl-museum", label: "Museum", tags: "museum after hours, marble, alarm light" },
  { id: "pl-or", label: "Operating room", tags: "operating room, harsh lamps, table" },
  { id: "pl-morgue", label: "Morgue", tags: "morgue, steel, cold, horror" },
  { id: "pl-crypt", label: "Crypt", tags: "crypt, stone shelves, dust, candles" },
  { id: "pl-sewer", label: "Sewer", tags: "sewer tunnel, wet brick, grate light" },
  { id: "pl-fireesc", label: "Fire escape", tags: "fire escape, city night, rail" },
  { id: "pl-balcony", label: "Balcony", tags: "balcony, city, someone could see" },
  { id: "pl-window", label: "Window", tags: "against the window, street below" },
  { id: "pl-studio", label: "Photo studio", tags: "photo studio, seamless, strobes" },
  { id: "pl-darkroom", label: "Darkroom", tags: "photo darkroom, red light, trays" },
  { id: "pl-aqua", label: "Aquarium", tags: "aquarium tunnel, blue light, fish" },
  { id: "pl-planet", label: "Planetarium", tags: "planetarium, stars on the ceiling" },
  { id: "pl-church2", label: "Confessional", tags: "confessional booth, screen, blasphemy" },
  { id: "pl-altar", label: "Altar", tags: "on the altar, candles, chapel" },
  { id: "pl-grave", label: "On a grave", tags: "on a gravestone, night, cemetery" },
  { id: "pl-woods", label: "Clearing", tags: "forest clearing, moon, roots" },
  { id: "pl-cave2", label: "Cave pool", tags: "cave pool, black water, echo" },
  { id: "pl-throne2", label: "On the throne", tags: "on the throne, empty court, banners" },
  { id: "pl-dungeon2", label: "Cell", tags: "dungeon cell, straw, chains" },
  { id: "pl-brothel", label: "Brothel", tags: "brothel room, red lamps, silk" },
  { id: "pl-strip", label: "Backstage", tags: "strip club backstage, mirrors, bulbs" },
  { id: "pl-vip", label: "VIP room", tags: "VIP room, couch, curtain" },
  { id: "pl-motel2", label: "By the hour", tags: "hourly motel, stained, neon" },
  { id: "pl-pent", label: "Glass penthouse", tags: "glass penthouse, city, exposed" },
  { id: "pl-kitchen2", label: "On the counter", tags: "kitchen counter, night, dishes" },
  { id: "pl-couch", label: "Couch", tags: "living room couch, TV glow" },
  { id: "pl-floor2", label: "On the rug", tags: "on the rug, living room, messy" },
  { id: "pl-closet", label: "Closet", tags: "in the closet, coats, hiding" },
  { id: "pl-attic2", label: "Attic mattress", tags: "attic mattress, dust, slats" },
  { id: "pl-shed", label: "Shed", tags: "garden shed, tools, dirt floor" },
  { id: "pl-barn", label: "Barn", tags: "barn, hay, lantern" },
  { id: "pl-stable", label: "Stable", tags: "stable, stalls, tack" },
  { id: "pl-dock2", label: "Pier", tags: "wooden pier, black water, fog" },
];

export const CAM_MORE: Bit[] = [
  { id: "cam-bird", label: "Bird's eye", tags: "bird's eye view, from above" },
  { id: "cam-cowboy", label: "Cowboy shot", tags: "cowboy shot, mid-thigh up" },
  { id: "cam-medium", label: "Medium", tags: "medium shot, waist up" },
  { id: "cam-insert", label: "Insert", tags: "insert shot, detail of the act" },
  { id: "cam-legs", label: "Through legs", tags: "shot between someone's legs" },
  { id: "cam-puddle", label: "Puddle", tags: "reflection in a puddle" },
  { id: "cam-cctv", label: "CCTV", tags: "CCTV angle, timestamp, grain" },
  { id: "cam-gopro", label: "GoPro", tags: "GoPro wide, close, distorted" },
  { id: "cam-selfie", label: "Selfie", tags: "selfie angle, arm in frame" },
  { id: "cam-anamorphic", label: "Anamorphic", tags: "anamorphic widescreen, flares" },
  { id: "cam-fisheye", label: "Fisheye", tags: "fisheye lens, bent room" },
  { id: "cam-tilt", label: "Tilt-shift", tags: "tilt-shift, miniature look" },
  { id: "cam-drone", label: "Drone", tags: "drone view, looking down" },
  { id: "cam-stead", label: "Steadicam", tags: "steadicam, following" },
  { id: "cam-profile", label: "Profile", tags: "strict profile, silhouette" },
  { id: "cam-3q", label: "Three-quarter", tags: "three-quarter view" },
  { id: "cam-overhead", label: "Overhead bed", tags: "overhead, looking down at the bed" },
  { id: "cam-under", label: "From below act", tags: "from below, looking up at the act" },
  { id: "cam-eye", label: "Eye level", tags: "eye level, documentary" },
  { id: "cam-hip", label: "Hip height", tags: "camera at hip height" },
  { id: "cam-ground", label: "On the ground", tags: "camera on the ground, cheek to floor" },
  { id: "cam-mirror2", label: "Bathroom mirror", tags: "bathroom mirror selfie, steam" },
  { id: "cam-split", label: "Split diopter", tags: "split diopter, face and act sharp" },
  { id: "cam-rack", label: "Rack focus", tags: "rack focus, face to where they join" },
];

export const LIGHT_MORE: Bit[] = [
  { id: "lit-bluehour", label: "Blue hour", tags: "blue hour, cold dusk" },
  { id: "lit-tungsten", label: "Tungsten", tags: "tungsten bulbs, warm orange" },
  { id: "lit-fluor", label: "Fluorescent", tags: "sick fluorescent, green cast" },
  { id: "lit-led", label: "LED", tags: "cheap LED, hard, magenta" },
  { id: "lit-ring", label: "Ring light", tags: "ring light, catchlights, influencer" },
  { id: "lit-spot", label: "Spotlight", tags: "single spotlight, black around" },
  { id: "lit-god", label: "God rays", tags: "god rays through dust" },
  { id: "lit-caustic", label: "Caustics", tags: "water caustics on skin" },
  { id: "lit-bio", label: "Biolume", tags: "bioluminescence, cold glow" },
  { id: "lit-eclipse", label: "Eclipse", tags: "eclipse light, wrong noon" },
  { id: "lit-headlight", label: "Headlights", tags: "car headlights, hard, dust" },
  { id: "lit-tv", label: "TV glow", tags: "TV glow on bodies, dark room" },
  { id: "lit-monitor", label: "Monitor", tags: "computer monitor light, blue" },
  { id: "lit-flash", label: "Flashlight", tags: "flashlight beam, rest black" },
  { id: "lit-lantern", label: "Lantern", tags: "lantern, swinging, warm" },
  { id: "lit-torch", label: "Torch", tags: "torch, smoke, orange" },
  { id: "lit-bounce", label: "Bounce", tags: "bounced fill, soft, close" },
  { id: "lit-beauty", label: "Beauty dish", tags: "beauty dish, fashion, hard-soft" },
  { id: "lit-split", label: "Split light", tags: "split lighting, half face black" },
  { id: "lit-rembrandt", label: "Rembrandt", tags: "Rembrandt triangle, painterly" },
  { id: "lit-silhouette2", label: "Backlit", tags: "backlit, rim, face in dark" },
  { id: "lit-strobe", label: "Strobe freeze", tags: "strobe freeze, droplets sharp" },
  { id: "lit-blacklight", label: "Blacklight", tags: "blacklight, fluids glow" },
  { id: "lit-emergency", label: "Emergency", tags: "emergency red, alarm" },
];

export const MORE_MORE: Bit[] = [
  { id: "more-pores", label: "Pores", tags: "visible pores, real skin" },
  { id: "more-sweat2", label: "Sweat beads", tags: "sweat beads, running" },
  { id: "more-spit", label: "Spit", tags: "spit strings, wet chin" },
  { id: "more-cum", label: "Cum visible", tags: "cum visible, thick, dripping" },
  { id: "more-vein", label: "Vascular", tags: "vascular, veins standing" },
  { id: "more-weight", label: "Weight", tags: "body weight, squash, contact" },
  { id: "more-grip", label: "Grip", tags: "hands gripping hard, white knuckles" },
  { id: "more-shake", label: "Shaking", tags: "shaking, muscle tremor" },
  { id: "more-breath", label: "Breath", tags: "breath fog, open mouth" },
  { id: "more-noise", label: "Room tone", tags: "lived-in, mess, not a set" },
  { id: "more-raw", label: "Raw", tags: "raw, unflattering, honest" },
  { id: "more-glam", label: "Glam", tags: "glam, retouched, studio" },
  { id: "more-doc", label: "Documentary", tags: "documentary still, available light" },
  { id: "more-hentai", label: "Hentai grade", tags: "uncensored hentai, explicit anatomy" },
  { id: "more-photo", label: "Photo grade", tags: "photograph, real, 35mm" },
  { id: "more-paint", label: "Painted", tags: "painted, brush, not photo" },
  { id: "more-nsfw", label: "NSFW stamp", tags: "nsfw, explicit, uncensored, 18+" },
  { id: "more-noface", label: "No crop face", tags: "face in frame, not cropped" },
  { id: "more-nofeet", label: "Feet in", tags: "feet in frame" },
  { id: "more-hands2", label: "Both hands", tags: "both hands visible, five fingers" },
];

export const COMIC_MORE: Bit[] = [
  { id: "comic-shonen", label: "Shonen", tags: "shonen manga, speed lines, impact" },
  { id: "comic-josei", label: "Josei", tags: "josei manga, adult women, realistic" },
  { id: "comic-ecchi", label: "Ecchi", tags: "ecchi manga, fanservice, uncensored" },
  { id: "comic-hentai", label: "Hentai page", tags: "hentai manga page, explicit, uncensored, 18+" },
  { id: "comic-doujin", label: "Doujin", tags: "doujinshi, xerox grain, explicit" },
  { id: "comic-bara", label: "Bara comic", tags: "bara manga, muscular men, explicit" },
  { id: "comic-yaoi", label: "BL comic", tags: "boys love manga, explicit adult" },
  { id: "comic-yuri", label: "GL comic", tags: "yuri manga, explicit adult" },
  { id: "comic-guro", label: "Guro", tags: "guro manga, gore, explicit, 18+" },
  { id: "comic-horror2", label: "Ito", tags: "Ito-like horror manga, spirals, viscera" },
  { id: "comic-pulp", label: "Pulp", tags: "pulp magazine cover, painted, lurid" },
  { id: "comic-underground", label: "Underground", tags: "underground comix, crude, ink" },
  { id: "comic-euro", label: "Heavy Metal", tags: "Heavy Metal magazine, euro erotic, painted" },
  { id: "comic-moebius", label: "Moebius", tags: "Moebius line, weird, clean" },
  { id: "comic-crumb", label: "Crumb", tags: "Crumb-like, crosshatch, grotesque erotic" },
  { id: "comic-webtoon", label: "Webtoon", tags: "full color webtoon, vertical, clean" },
  { id: "comic-chiar", label: "High contrast ink", tags: "high contrast comic ink, no grey" },
  { id: "comic-color", label: "Flat color", tags: "flat comic color, bold hold" },
  { id: "comic-screentone", label: "Screentone heavy", tags: "heavy screentones, manga grey" },
];

export const EVIL_MORE: Bit[] = [
  { id: "evil-hunt", label: "Hunted", tags: "hunted through the woods, caught, explicit, 18+" },
  { id: "evil-trap", label: "Trapped", tags: "trapped in the room, door blocked, explicit, 18+" },
  { id: "evil-drugged", label: "Drugged look", tags: "heavy lids, compliant, drugged look, adult 18+" },
  { id: "evil-sold", label: "Sold", tags: "sold, inspected, used, adult 18+" },
  { id: "evil-claimed", label: "Claimed", tags: "claimed, marked, his now, explicit" },
  { id: "evil-broken", label: "Broken", tags: "broken, no fight left, still being used, 18+" },
  { id: "evil-audience", label: "Audience", tags: "people watching, she cannot leave, explicit, 18+" },
  { id: "evil-film", label: "Filmed", tags: "camera in his hand, filming it, forced, 18+" },
  { id: "evil-mask", label: "Masked men", tags: "masked men, no faces, using her, 18+" },
  { id: "evil-van", label: "Van", tags: "in a van, night, forced, adult 18+" },
  { id: "evil-woods", label: "Woods rape", tags: "woods, dirt, forced, adult 18+" },
  { id: "evil-home", label: "Home invasion", tags: "home invasion, living room, forced, 18+" },
  { id: "evil-altar2", label: "Sacrifice sex", tags: "altar, sacrifice aesthetic, used, 18+" },
  { id: "evil-demon2", label: "Hell claim", tags: "hell, demons, claimed body, explicit" },
  { id: "evil-witch2", label: "Coven", tags: "coven, they take her, ritual sex, 18+" },
  { id: "evil-vampire2", label: "Bloodfuck", tags: "fangs in while fucking, blood, 18+" },
  { id: "evil-zombie", label: "Undead use", tags: "undead, rotting hands, using her, horror, 18+" },
  { id: "evil-nohelp", label: "No help", tags: "she looks at us, no help coming, explicit, 18+" },
  { id: "evil-laugh", label: "They laugh", tags: "they laugh while they do it, explicit, 18+" },
  { id: "evil-recording", label: "Livestreamed", tags: "livestreamed, chat, forced, adult 18+" },
  { id: "evil-blackbag", label: "Hooded", tags: "black bag over the head, used, 18+" },
  { id: "evil-zip", label: "Zipties", tags: "zipties, concrete floor, forced, 18+" },
];

export const LOOK_MORE: Bit[] = [
  { id: "look-oilbar", label: "Oil bar", tags: "oil stick drawing, dense pigment" },
  { id: "look-charcoal", label: "Charcoal", tags: "charcoal on paper, smudge, life drawing" },
  { id: "look-gouache", label: "Gouache", tags: "gouache illustration, matte, designy" },
  { id: "look-watercolor", label: "Watercolor", tags: "watercolor, paper tooth, blooms" },
  { id: "look-airbrush", label: "Airbrush", tags: "70s airbrush, soft, chrome, pinup" },
  { id: "look-pinup", label: "Pin-up", tags: "vintage pin-up, Vargas, painted" },
  { id: "look-playboy", label: "70s centerfold", tags: "1970s centerfold photo, grain, flash" },
  { id: "look-nugo", label: "Nude polaroid", tags: "instant nude polaroid, flash, amateur" },
  { id: "look-araki", label: "Araki", tags: "Araki-like, kinbaku, polaroid, flowers" },
  { id: "look-mapple", label: "Mapplethorpe", tags: "Mapplethorpe-like, studio, black, explicit" },
  { id: "look-nan", label: "Nan Goldin", tags: "Nan Goldin-like, flash, intimate, messy" },
  { id: "look-nobu", label: "Nobuyoshi", tags: "high contrast Japanese erotic photo" },
  { id: "look-hentai2", label: "Nitroplus", tags: "visual novel CG, explicit, detailed" },
  { id: "look-tifa", label: "FF7 CG", tags: "FF7 remake CG, pore skin, cinematic" },
  { id: "look-blade", label: "Blade Runner", tags: "blade runner still, rain, neon, smoke" },
  { id: "look-berserk", label: "Berserk", tags: "Berserk manga, grit, crosshatch, dark" },
  { id: "look-clay", label: "Clay", tags: "claymation still, fingerprints" },
  { id: "look-stop", label: "Stop motion", tags: "stop-motion puppet, felt, armature" },
  { id: "look-80s", label: "80s photo", tags: "1980s photo, push process, magenta" },
  { id: "look-00s", label: "Early digital", tags: "early 2000s digital, compact flash, hard" },
  { id: "look-cctv2", label: "Night vision", tags: "night vision green, grain, IR" },
  { id: "look-thermal", label: "Thermal", tags: "thermal camera, heat bodies" },
  { id: "look-scan", label: "Flatbed scan", tags: "flatbed scan, crushed against glass" },
  { id: "look-xerox", label: "Xerox", tags: "xerox, crushed blacks, dirty" },
  { id: "look-woodcut", label: "Woodcut", tags: "woodcut print, heavy blacks" },
  { id: "look-etch", label: "Etching", tags: "etching, fine hatch, plate tone" },
  { id: "look-icon", label: "Icon", tags: "orthodox icon, gold, egg tempera" },
  { id: "look-fresco", label: "Fresco", tags: "fresco, plaster, chapel wall" },
  { id: "look-baroque", label: "Baroque", tags: "baroque painting, flesh, dark ground" },
  { id: "look-symbolist", label: "Symbolist", tags: "symbolist painting, sick jewels, myth" },
];

export const NSFW_MORE: NsfwBit[] = [
  { id: "rimming", label: "Rimming", tags: "rimming, face in ass, tongue, explicit", group: "Sex" },
  { id: "facial", label: "Facial", tags: "facial, cum on face, dripping, explicit", group: "Sex" },
  { id: "swallow", label: "Swallow", tags: "swallowing cum, throat, messy, explicit", group: "Sex" },
  { id: "squirting", label: "Squirting", tags: "squirting, wet, shaking, explicit", group: "Sex" },
  { id: "fisting", label: "Fisting", tags: "fisting, stretched, wrist, explicit", group: "Sex" },
  { id: "gape", label: "Gape", tags: "gaping hole, wrecked, explicit", group: "Sex" },
  { id: "cervix", label: "Cervix", tags: "cock against cervix, bulge, explicit", group: "Sex" },
  { id: "womb", label: "Womb bulge", tags: "womb bulge, stomach outline of cock, explicit", group: "Sex" },
  { id: "da", label: "Double anal", tags: "double anal, two cocks, stretched, explicit", group: "Sex" },
  { id: "dv", label: "Double vag", tags: "double vaginal, stretched, explicit", group: "Sex" },
  { id: "triple", label: "Triple", tags: "triple penetration, filled, explicit", group: "Sex" },
  { id: "paizuri", label: "Paizuri", tags: "paizuri, cock between breasts, explicit", group: "Sex" },
  { id: "thighjob", label: "Thighjob", tags: "thighjob, cock between thighs, explicit", group: "Sex" },
  { id: "intercrural", label: "Intercrural", tags: "intercrural, no entry, sliding, explicit", group: "Sex" },
  { id: "frottage", label: "Frottage", tags: "frottage, grinding clothed then not, explicit", group: "Sex" },
  { id: "cumdump", label: "Cumdump", tags: "cumdump, used, dripping from everywhere, explicit", group: "Sex" },
  { id: "creampie3", label: "Overflow", tags: "creampie overflow, too much, leaking, explicit", group: "Sex" },
  { id: "prostate", label: "Prostate", tags: "prostate, him shaking, pegged or fucked, explicit", group: "Sex" },
  { id: "autofellatio", label: "Autofellatio", tags: "autofellatio, flexible, explicit", group: "Sex" },
  { id: "sounding", label: "Sounding", tags: "urethral sounding, rod, explicit", group: "BDSM" },
  { id: "cbt", label: "CBT", tags: "cock and ball torture, squeezed, explicit", group: "BDSM" },
  { id: "figging", label: "Figging", tags: "figging, ginger, flinching, explicit", group: "BDSM" },
  { id: "needle", label: "Needles", tags: "play piercing, needles in skin, explicit, 18+", group: "BDSM" },
  { id: "gimp", label: "Gimp", tags: "gimp suit, zipper mouth, used, explicit", group: "BDSM" },
  { id: "gasmask", label: "Gas mask", tags: "gas mask, muffled, latex, explicit", group: "BDSM" },
  { id: "sleepsack", label: "Sleepsack", tags: "sleepsack, mummified, only mouth, explicit", group: "BDSM" },
  { id: "ponyplay", label: "Pony play", tags: "pony play, bit, hooves, plugged, explicit", group: "BDSM" },
  { id: "puppyplay", label: "Puppy play", tags: "puppy play, hood, bowl, explicit", group: "BDSM" },
  { id: "kennel", label: "Kennel", tags: "in a kennel, pet, used, explicit", group: "BDSM" },
  { id: "queening", label: "Queening", tags: "queening, sitting on his face, smother, explicit", group: "BDSM" },
  { id: "trampling", label: "Trample", tags: "trampled, heels on him, explicit", group: "BDSM" },
  { id: "shibari2", label: "Shibari", tags: "shibari, full harness, artful rope, explicit", group: "BDSM" },
  { id: "predicament2", label: "Predicament", tags: "predicament bondage, on tiptoes, explicit", group: "BDSM" },
  { id: "stockade", label: "Stockade", tags: "wooden stocks, bent, accessible, explicit", group: "BDSM" },
  { id: "cross", label: "St. Andrew", tags: "St. Andrew's cross, strapped, explicit", group: "BDSM" },
  { id: "standingdog", label: "Standing doggy", tags: "standing doggy, bent, from behind, explicit", group: "Positions" },
  { id: "seated", label: "Seated fuck", tags: "seated, in his lap, grinding, explicit", group: "Positions" },
  { id: "folded", label: "Folded", tags: "folded in half, knees to ears, explicit", group: "Positions" },
  { id: "nordic", label: "Nordic", tags: "nordic, she on side, one leg up, explicit", group: "Positions" },
  { id: "irish", label: "Irish spoon", tags: "irish spooning, facing, legs, explicit", group: "Positions" },
  { id: "reversemiss", label: "Reverse missionary", tags: "reverse missionary, he on his back, she down, explicit", group: "Positions" },
  { id: "frombehindoral", label: "Oral from behind", tags: "eating her from behind, ass up, explicit", group: "Positions" },
  { id: "rimmingpos", label: "Rimming pose", tags: "ass up, face in, rimming, explicit", group: "Positions" },
  { id: "sideoral", label: "Side oral", tags: "lying on the side, sucking, explicit", group: "Positions" },
  { id: "kneespread", label: "Knees spread", tags: "on her back, knees spread wide, explicit", group: "Positions" },
  { id: "standingcarry2", label: "Pinned lift", tags: "pinned to the wall, lifted, explicit", group: "Positions" },
  { id: "cowgirllean", label: "Cowgirl lean", tags: "cowgirl leaning forward, hands on chest, explicit", group: "Positions" },
  { id: "lich", label: "Lich", tags: "lich, rotting grandeur, magic, fucking her, explicit", group: "Creatures" },
  { id: "ghoul", label: "Ghoul", tags: "ghoul, grave dirt, biting, explicit, 18+", group: "Creatures" },
  { id: "gargoyle", label: "Gargoyle", tags: "gargoyle, stone, wings, cathedral, mounting, explicit", group: "Creatures" },
  { id: "griffin", label: "Griffin", tags: "griffin, talons, nest, size, explicit", group: "Creatures" },
  { id: "hydra", label: "Hydra", tags: "hydra, many heads, wrapping, explicit", group: "Creatures" },
  { id: "cerberus", label: "Cerberus", tags: "cerberus, three heads, underworld, explicit", group: "Creatures" },
  { id: "cyclops", label: "Cyclops", tags: "cyclops, huge, cave, mounting, explicit", group: "Creatures" },
  { id: "troll", label: "Troll", tags: "troll, bridge, huge, dumb, breeding, explicit", group: "Creatures" },
  { id: "ogre", label: "Ogre", tags: "ogre, fat muscle, stink, claiming, explicit", group: "Creatures" },
  { id: "kobold", label: "Kobold", tags: "kobolds, small, pack, swarming her, explicit", group: "Creatures" },
  { id: "mermaid", label: "Mermaid", tags: "mermaid, tail, underwater, explicit sex", group: "Creatures" },
  { id: "siren", label: "Siren", tags: "siren, rocks, wreck, dragging him under, explicit", group: "Creatures" },
  { id: "angel", label: "Angel", tags: "angel, white wings, ruined, explicit", group: "Creatures" },
  { id: "nephilim", label: "Nephilim", tags: "nephilim, giant, hybrid, explicit", group: "Creatures" },
  { id: "djinn", label: "Djinn", tags: "djinn, smoke, lamp, wishes paid in body, explicit", group: "Creatures" },
  { id: "ifrit", label: "Ifrit", tags: "ifrit, fire, brass, claiming, explicit", group: "Creatures" },
  { id: "yokai", label: "Yokai", tags: "yokai, Japanese spirit, uncanny, explicit", group: "Creatures" },
  { id: "kappa", label: "Kappa", tags: "kappa, river, shell, explicit adult", group: "Creatures" },
  { id: "tengu", label: "Tengu", tags: "tengu, long nose, mountain, explicit", group: "Creatures" },
  { id: "skinwalker", label: "Skinwalker", tags: "skinwalker, wrong animal, horror sex, 18+", group: "Creatures" },
  { id: "mothman", label: "Mothman", tags: "mothman, red eyes, wings, bridge, explicit", group: "Creatures" },
  { id: "xeno", label: "Xenomorph", tags: "xenomorph, inner jaw, tubes, ovipositor, explicit adult", group: "Creatures" },
  { id: "parasite", label: "Parasite", tags: "parasite, under skin, using the body, explicit, 18+", group: "Creatures" },
  { id: "teacher", label: "Teacher", tags: "adult teacher and adult student, after class, 18+", group: "Taboo" },
  { id: "coach", label: "Coach", tags: "adult coach, locker, power, 18+", group: "Taboo" },
  { id: "therapist", label: "Therapist", tags: "therapist, couch, unethical, adult 18+", group: "Taboo" },
  { id: "bodyguard", label: "Bodyguard", tags: "bodyguard, hotel suite, they shouldn't, 18+", group: "Taboo" },
  { id: "stranger", label: "Stranger", tags: "stranger, just met, bathroom, explicit, 18+", group: "Taboo" },
  { id: "cuckquean", label: "Cuckquean", tags: "cuckquean, she watches him take another, 18+", group: "Taboo" },
  { id: "sharing", label: "Shared", tags: "shared partner, they agreed, still raw, 18+", group: "Taboo" },
  { id: "recording2", label: "Secret cam", tags: "secret camera, they don't know, explicit, 18+", group: "Taboo" },
  { id: "incestrole", label: "Family RP", tags: "adult family-roleplay, all 18+, forbidden talk, explicit", group: "Taboo" },
  { id: "flay", label: "Flay", tags: "flaying, skin, blood, horror, adult 18+", group: "Horror" },
  { id: "dismember", label: "Dismember", tags: "dismemberment, blood, horror still, 18+", group: "Horror" },
  { id: "eyegore", label: "Eye gore", tags: "eye trauma, horror close-up, 18+", group: "Horror" },
  { id: "drown", label: "Drown", tags: "drowning, underwater, horror, 18+", group: "Horror" },
  { id: "buried", label: "Buried", tags: "buried, dirt, hands, horror, 18+", group: "Horror" },
  { id: "hooked2", label: "Meat hook", tags: "meat hook, hanging, slaughterhouse, 18+", group: "Horror" },
  { id: "saw2", label: "Saw", tags: "industrial saw, gore, 18+", group: "Horror" },
  { id: "crucifix", label: "Crucifixion", tags: "crucifixion aesthetic, blood, horror, 18+", group: "Horror" },
  { id: "necks", label: "Throat cut", tags: "throat cut, arterial spray, horror, 18+", group: "Horror" },
  { id: "gut", label: "Disembowel", tags: "disembowel, viscera, hands in, 18+", group: "Horror" },
];
